application:
  title: Feed Service
  version: 1.0

server:
  port: 8087

spring:
  application:
    name: feed-service
  rabbitmq:
    host: 172.20.0.3
  data:
    mongodb:
      database: comments
      port: 27017
      username: test
      password: pass
      authentication-database: admin
      auto-index-creation: true
      host: localhost
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus