application:
  title: Feed Service
  version: 1.0

server:
  port: 8087

spring:
  application:
    name: feed-service
  rabbitmq:
    host: ${host_rabbit}

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
